apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-java
  template:
    metadata:
      labels:
        app: docker-java
    spec:
      containers:
        - name: docker-java
          image: pavel7777766666/docker-java:latest
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-0.kafka:9092,kafka-1.kafka:9092,kafka-2.kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: docker-java
spec:
  type: LoadBalancer
  selector:
    app: docker-java
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088